# Generated by Django 3.0.3 on 2020-02-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_source_and_unique_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='ability',
            field=models.CharField(choices=[('str', 'Strength'), ('dex', 'Dexterity'), ('con', 'Constitution'), ('int', 'Intelligence'), ('wis', 'Wisdom'), ('cha', 'Charisma')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
