# Generated by Django 3.0.3 on 2020-03-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterability',
            old_name='value',
            new_name='initial_value',
        ),
        migrations.RenameField(
            model_name='characterskill',
            old_name='proficiency',
            new_name='initial_proficiency',
        ),
    ]
