# Generated by Django 3.0.3 on 2020-03-24 11:36

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models

import characters.utils


class Migration(migrations.Migration):

    dependencies = [
        ('creatures', '0001_initial'),
        ('characters', '0002_rename_character_ability_value_and_character_skill_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='creatures.Race'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characterdetails',
            name='portrait',
            field=django_resized.forms.ResizedImageField(crop=('top', 'right'), force_format=None, keep_meta=True, null=True, quality=0, size=(300, 300), upload_to=characters.utils.portrait_upload_to),
        ),
    ]
