# Generated by Django 3.0.3 on 2020-03-24 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_drop_ability_and_update_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_exotic', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('age', models.TextField(blank=True)),
                ('alignment', models.TextField(blank=True)),
                ('climb_speed', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('climb_speed_description', models.TextField(blank=True)),
                ('flight_speed', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('flight_speed_description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('size_description', models.TextField(blank=True)),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('speed_description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(unique=True)),
                ('space', models.CharField(max_length=50)),
                ('value', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RacialSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('proficiency', models.CharField(choices=[('proficiency', 'Proficiency'), ('expertise', 'Expertise')], default='proficiency', max_length=11)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_skills', to='creatures.Race')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_skills', to='core.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RacialLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_languages', to='creatures.Language')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_languages', to='creatures.Race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RacialAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ability', models.CharField(choices=[('str', 'Strength'), ('dex', 'Dexterity'), ('con', 'Constitution'), ('int', 'Intelligence'), ('wis', 'Wisdom'), ('cha', 'Charisma')], max_length=3)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)])),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_abilities', to='creatures.Race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.ManyToManyField(related_name='races', through='creatures.RacialLanguage', to='creatures.Language'),
        ),
        migrations.AddField(
            model_name='race',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='creatures.Size'),
        ),
        migrations.AddField(
            model_name='race',
            name='skills',
            field=models.ManyToManyField(related_name='races', through='creatures.RacialSkill', to='core.Skill'),
        ),
        migrations.AddField(
            model_name='race',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='core.Source'),
        ),
        migrations.AddField(
            model_name='language',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='creatures.Script'),
        ),
    ]
