# Generated by Django 3.0.3 on 2020-03-26 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_condition_and_damage_type'),
        ('creatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacialSense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_senses', to='creatures.Race')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_senses', to='creatures.Sense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RacialResistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('advantage', 'Advantage'), ('resistance', 'Resistance'), ('immunity', 'Immunity'), ('vulnerability', 'Vulnerability')], max_length=13)),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racial_resistances', to='core.Condition')),
                ('damage_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racial_resistances', to='core.DamageType')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_resistances', to='creatures.Race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RacialFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_features', to='core.Feature')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racial_features', to='creatures.Race')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
